require('ishan.plugins.lir')
require('ishan.plugins.devicons')
require('ishan.plugins.expressline')
require('ishan.plugins.fterm')
require('ishan.plugins.lspconfig')
require('ishan.plugins.telescope')
require('ishan.plugins.compe')
require('ishan.plugins.truezen')
require('ishan.plugins.nvr')
-- require('ishan.plugins.treesitter')
